
SOLVER:
  OPTIMIZER_NAME: "Adam"
  BASE_LR: 0.0004
  WEIGHT_DECAY: 0.0000000
  IMS_PER_BATCH: 1
  START_ITERS: 3000
  END_ITERS: 60000
  LR_SCALE: 0.09
  WARMUP_ITERS: 1000

  MAX_EPOCHS: 100
  CHECKPOINT_PERIOD: 3000
  LOG_PERIOD: 30
  BUNCH: 3000
  COARSE_STAGE: 3

INPUT:
  SIZE_TRAIN: [600,900]
  SIZE_TEST: [600,900]

DATASETS:
  #TRAIN: "/data/wmy/NR/dataset/sport_1_small"
  TRAIN: "/data/panganqi"
  NUM_FRAME: 1
  SHIFT: 0.0
  MAXRATION: 0.0
  ROTATION: 0.0
  
  USE_MASK: False

MODEL:
  COARSE_RAY_SAMPLING: 50
  FINE_RAY_SAMPLING: 32
  SAMPLE_METHOD: "NEAR_FAR"       #  "NEAR_FAR"     "BBOX" 
  BOARDER_WEIGHT: 1e10
  SAME_SPACENET: True
  TKERNEL_INC_RAW: True

TEST:
  IMS_PER_BATCH: 1

OUTPUT_DIR: "/data/panganqi_nearfar_s_ori"
